#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################

services:
  omop_es:
    extends:
      file: docker-compose.yml
      service: omop_es
    environment:
        DOCKER_USER_GID: ${DOCKER_USER_GID}
    volumes:
      - "sharefs6-criudata:/sharefs6/criudata/Live"
      - "sharefs7-crdm:/sharefs7/crdm/Shared"

  omop-cascade:
    extends:
      file: docker-compose.yml
      service: omop-cascade
    environment:
        DOCKER_USER_GID: ${DOCKER_USER_GID}
    volumes:
      - "./omop-cascade/app/conf:/app/conf"
      - "./omop-cascade/app/conn:/app/conn"
      - "./omop-cascade/app/ddl:/app/ddl"
      - "./omop-cascade/local:/share/local"
      - "sharefs6-criudata:/sharefs6/criudata/Live"
      - "sharefs7-crdm:/sharefs7/crdm/Shared"

volumes:
  sharefs6-criudata:
    driver: "local"
    driver_opts:
      type: "cifs"
      device: "${SHAREFS6_CRIUDATA}"
      o: "user=${USER_UID},domain=${USER_DOMAIN},password=${USER_PWD},uid=1001,gid=${DOCKER_USER_GID}"

  sharefs7-crdm:
    driver: "local"
    driver_opts:
      type: "cifs"
      device: "${SHAREFS7_CRDM}"
      o: "user=${USER_UID},domain=${USER_DOMAIN},password=${USER_PWD},uid=1001,gid=${DOCKER_USER_GID}"
