name: Run tests of Prefect flow and task code

on:
  push:
    branches: ["main"]
    paths: ["prefect/**"]
  pull_request:
    branches: ["main"]
    paths: ["prefect/**"]
  workflow_dispatch:

# Only run actions on the most recent push to a branch
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.1"

      - name: Use template environment files
        run: |
          cp template.env .env
          cp omop_es/template.env omop_es/.env
          cp omop-cascade/template.env omop-cascade/.env
          cp prefect/template.env prefect/.env

      - name: Run pytest
        working-directory: ./prefect
        env:
          GITHUB_PAT: ${{ secrets.OMOP_ES_GITHUB_PAT }}
        run: |
          make test
